import type { Metadata } from 'next'
import Header from '@/layouts/header';
import Footer from '@/layouts/footer';

import '@/styles/globals.css';
export const metadata: Metadata = {
  title: 'Nft Project',
  description: 'Generated by Nft Project',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className='flex flex-col items-center justify-between full'>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
